services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: carsolutions-tw-core:latest
    container_name: carsolutions-tw-core
    ports:
      - '3006:3006'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://147.182.128.232:3006',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  app-network:
    driver: bridge
