export const navData = [
  {
    id: 1,
    title: "Business Setup",
    url: "/business-setup-services-in-uae",
    view: "tabView",
    tabs: [
      {
        id: 1,
        title: "UAE Free Zone",
        url: "#",
        items: [
          {
            id: 1,
            title: "Dubai Free Zone",
            url: "#",
            links: [
              { id: 1, title: "DAFZ - Dubai Airport Free Zone", url: "#" },
              { id: 2, title: "DAZ - Dubai Auto Zone", url: "#" },
              { id: 3, title: "DIC - Dubai Internet City", url: "#" },
              { id: 4, title: "DMC - Dubai Media City", url: "#" },
              {
                id: 5,
                title: "DMCC - Dubai Multi Commodities Center",
                url: "#",
              },
              { id: 6, title: "DSO - Dubai Silicon Oasis", url: "#" },
              { id: 7, title: "Dubai South- Dubai South Free Zone", url: "#" },
              {
                id: 8,
                title: "DTEC - Dubai Technology Entrepreneur Center",
                url: "#",
              },
              {
                id: 9,
                title: "DWTC - Dubai World Trade Center Free Zone",
                url: "#",
              },
              { id: 10, title: "Expo City Dubai Free Zone", url: "#" },
              {
                id: 11,
                title: "IFZA - International Free Zone Authority",
                url: "#",
              },
              { id: 12, title: "MFZ - Meydan Free Zone", url: "#" },
              {
                id: 13,
                title: "TECOM - Technology Electronic Commerce and Media Group",
                url: "#",
              },
            ],
          },
          {
            id: 2,
            title: "Abu Dhabi Free zone",
            url: "#",
            links: [
              { id: 1, title: "ADGM - Abu Dhabi Global Market", url: "#" },
              {
                id: 2,
                title: "KIZAD - Khalifa Industrial Zone Abu Dhabi",
                url: "#",
              },
              { id: 3, title: "Twofour54 (Media & Creative)", url: "#" },
              { id: 4, title: "Masdar City Free Zone", url: "#" },
              { id: 5, title: "ADAFZ - Abu Dhabi Airport Free Zone", url: "#" },
            ],
          },
          {
            id: 3,
            title: "Sharjah Free Zone",
            url: "#",
            links: [
              {
                id: 1,
                title: "SPC - Sharjah Publishing City Free Zone",
                url: "#",
              },
              { id: 2, title: "HFZA - Hamriyah Free Zone", url: "#" },
              {
                id: 3,
                title: "SAIF - Sharjah Airport International free zone",
                url: "#",
              },
              {
                id: 4,
                title: "SHAMS - Sharjah Media City free zone",
                url: "#",
              },
            ],
          },
          {
            id: 4,
            title: "Ajman Free Zone",
            url: "#",
            links: [
              { id: 1, title: "AMC - Ajman Media City Free Zone", url: "#" },
            ],
          },
          {
            id: 5,
            title: "Ras Al Khaimah Free Zone",
            url: "#",
            links: [
              {
                id: 1,
                title: "RAKEZ - Ras Al Khaimah Economic Zone",
                url: "#",
              },
              { id: 2, title: "RAK Maritime City Free Zone", url: "#" },
              { id: 3, title: "RAK DAO - RAK Digital Assets Oasis", url: "#" },
            ],
          },
          {
            id: 6,
            title: "Umm Al Quwain Free Zone",
            url: "#",
            links: [
              { id: 1, title: "UAQ FTZ - Umm Al Quwain Free Zone", url: "#" },
            ],
          },
          {
            id: 7,
            title: "Fujairah Free Zone",
            url: "#",
            links: [{ id: 1, title: "FCC - Fujairah Creative City", url: "#" }],
          },
        ],
      },
      //=====================
      //=====================
      {
        id: 2,
        title: "UAE Mainland",
        url: "#",
        view: "childView",
        items: [
          {
            id: 1,
            title: "",
            url: "#",
            links: [
              { id: 1, title: "Dubai Mainland", url: "#" },
              { id: 2, title: "Abu Dhabi Mainland", url: "#" },
              { id: 3, title: "Ajman Mainland", url: "#" },
              { id: 4, title: "Sharjah Mainland", url: "#" },
            ],
          },
        ],
      },
      //=====================
      //=====================
      {
        id: 3,
        title: "UAE Offshore",
        view: "childView",
        url: "#",
        items: [
          {
            id: 1,
            title: "",
            url: "#",
            links: [
              { id: 1, title: "Dubai Offshore", url: "#" },
              { id: 2, title: "Jebel Ali Offshore", url: "#" },
              { id: 3, title: "Ras Al Khaimah Offshore", url: "#" },
              { id: 4, title: "Ajman Offshore", url: "#" },
            ],
          },
        ],
      },
      //=====================
      //=====================
      {
        id: 4,
        title: "Business Activities Consultancy",
        url: "#",
        items: [],
      },
      //=====================
      //=====================
      {
        id: 5,
        title: "Office Solutions",
        view: "childView",
        items: [
          {
            id: 1,
            title: "",
            url: "#",
            links: [
              { id: 1, title: "Physical Office Leasing", url: "#" },
              { id: 2, title: "Flexi Desk / Smart Desk Solutions", url: "#" },
              { id: 3, title: "Virtual Office Services", url: "#" },
              { id: 4, title: "Co-working Space Solutions", url: "#" },
            ],
          },
        ],
      },
      //=====================
      //=====================
      {
        id: 6,
        title: "Business License",
        url: "#",
        items: [
          {
            id: 1,
            title: "Free Zone License",
            url: "#",
            links: [
              { id: 1, title: "Commercial License", url: "#" },
              { id: 2, title: "Real Estate License", url: "#" },
              { id: 3, title: "Industrial License", url: "#" },
              { id: 4, title: "Professional License", url: "#" },
              { id: 5, title: "Dual License", url: "#" },
              { id: 6, title: "Crypto & Web3 License", url: "#" },
              { id: 7, title: "Event License", url: "#" },
              { id: 8, title: "E-commerce License ", url: "#" },
              { id: 9, title: "Freelancer Permit", url: "#" },
            ],
          },
          {
            id: 2,
            title: "Mainland Licence",
            links: [
              { id: 1, title: "Commercial License", url: "#" },
              { id: 2, title: "Real Estate License", url: "#" },
              { id: 3, title: "Event License", url: "#" },
              { id: 4, title: "E-commerce License ", url: "#" },
              { id: 5, title: "Crypto & Web3 License", url: "#" },
              { id: 6, title: "Industrial License", url: "#" },
              { id: 7, title: "Professional License", url: "#" },
            ],
          },
          {
            id: 3,
            title: "Business Licenses",
            links: [
              { id: 1, title: "Commercial License", url: "#" },
              { id: 2, title: "Real Estate License", url: "#" },
              { id: 3, title: "Industrial License", url: "#" },
              { id: 4, title: "Professional License", url: "#" },
              { id: 5, title: "Crypto & Web3 License", url: "#" },
              { id: 6, title: "Event License", url: "#" },
              { id: 7, title: "E-commerce License", url: "#" },
              { id: 7, title: "Freelancer Permit", url: "#" },
            ],
          },
        ],
      },
      //=====================
      //=====================
      {
        id: 7,
        title: "PRO Services UAE",
        items: [
          {
            id: 1,
            title: "PRO Services Dubai",
            links: [
              { id: 1, title: "Copyright Registration", url: "#" },
              { id: 2, title: "Company Registration", url: "#" },
              { id: 3, title: "Trade Name Reservation", url: "#" },
              { id: 4, title: "Trademark Registration & Renewal", url: "#" },
              { id: 5, title: "License Registration & Renewal", url: "#" },
              { id: 6, title: "VAT Registration & Filing", url: "#" },
              {
                id: 7,
                title: "Ejari (Tenancy Contract Registration)",
                url: "#",
              },
              { id: 8, title: "Corporate Tax Registration & Filing", url: "#" },
              { id: 9, title: "Document Attestation", url: "#" },
              { id: 10, title: "Legal Translation", url: "#" },
              { id: 11, title: "Power of Attorney Drafting", url: "#" },
              { id: 12, title: "Notarisation Services", url: "#" },
              {
                id: 13,
                title: "Economic Substance Regulation (ESR) Filing",
                url: "#",
              },
              {
                id: 14,
                title: "Ultimate Beneficial Owner (UBO) Filing",
                url: "#",
              },
            ],
          },
          {
            id: 2,
            title: "PRO Services Abu Dhabi",
            links: [
              { id: 1, title: "Copyright Registration", url: "#" },
              { id: 2, title: "Company Registration", url: "#" },
              { id: 3, title: "Trade Name Reservation", url: "#" },
              { id: 4, title: "Trademark Registration & Renewal", url: "#" },
              { id: 5, title: "License Registration & Renewal", url: "#" },
              { id: 6, title: "VAT Registration & Filing", url: "#" },
              {
                id: 7,
                title: "Ejari (Tenancy Contract Registration)",
                url: "#",
              },
              { id: 8, title: "Corporate Tax Registration & Filing", url: "#" },
              { id: 9, title: "Document Attestation", url: "#" },
              { id: 10, title: "Legal Translation", url: "#" },
              { id: 11, title: "Power of Attorney Drafting", url: "#" },
              { id: 12, title: "Notarisation Services", url: "#" },
              {
                id: 13,
                title: "Economic Substance Regulation (ESR) Filing",
                url: "#",
              },
              {
                id: 14,
                title: "Ultimate Beneficial Owner (UBO) Filing",
                url: "#",
              },
            ],
          },
          {
            id: 3,
            title: "PRO Services Sharjah",
            links: [
              { id: 1, title: "Copyright Registration", url: "#" },
              { id: 2, title: "Company Registration", url: "#" },
              { id: 3, title: "Trade Name Reservation", url: "#" },
              { id: 4, title: "Trademark Registration & Renewal", url: "#" },
              { id: 5, title: "License Registration & Renewal", url: "#" },
              { id: 6, title: "VAT Registration & Filing", url: "#" },
              {
                id: 7,
                title: "Ejari (Tenancy Contract Registration)",
                url: "#",
              },
              { id: 8, title: "Corporate Tax Registration & Filing", url: "#" },
              { id: 9, title: "Document Attestation", url: "#" },
              { id: 10, title: "Legal Translation", url: "#" },
              { id: 11, title: "Power of Attorney Drafting", url: "#" },
              { id: 12, title: "Notarisation Services", url: "#" },
              {
                id: 13,
                title: "Economic Substance Regulation (ESR) Filing",
                url: "#",
              },
              {
                id: 14,
                title: "Ultimate Beneficial Owner (UBO) Filing",
                url: "#",
              },
            ],
          },
          {
            id: 4,
            title: "PRO Services Ajman",
            links: [
              { id: 1, title: "Copyright Registration", url: "#" },
              { id: 2, title: "Company Registration", url: "#" },
              { id: 3, title: "Trade Name Reservation", url: "#" },
              { id: 4, title: "Trademark Registration & Renewal", url: "#" },
              { id: 5, title: "License Registration & Renewal", url: "#" },
              { id: 6, title: "VAT Registration & Filing", url: "#" },
              {
                id: 7,
                title: "Ejari (Tenancy Contract Registration)",
                url: "#",
              },
              { id: 8, title: "Corporate Tax Registration & Filing", url: "#" },
              { id: 9, title: "Document Attestation", url: "#" },
              { id: 10, title: "Legal Translation", url: "#" },
              { id: 11, title: "Power of Attorney Drafting", url: "#" },
              { id: 12, title: "Notarisation Services", url: "#" },
              {
                id: 13,
                title: "Economic Substance Regulation (ESR) Filing",
                url: "#",
              },
              {
                id: 14,
                title: "Ultimate Beneficial Owner (UBO) Filing",
                url: "#",
              },
            ],
          },
        ],
      },
      //=====================
    ],
  },
  {
    id: 2,
    title: "Corporate Services",
    url: "/corporate-services-in-uae",
    view: "parentChildView",
    items: [
      {
        id: 1,
        title: "Accounting Services",
        links: [
          { id: 1, title: "Payroll Management", url: "#" },
          { id: 2, title: "VAT & Tax Consultancy", url: "#" },
          { id: 3, title: "Corporate Tax", url: "#" },
        ],
      },
      {
        id: 2,
        title: "Compliance Services",
        links: [
          { id: 1, title: "AML Certificate", url: "#" },
          { id: 2, title: "Audit Services", url: "#" },
          { id: 3, title: "Tax Residency Certificate", url: "#" },
          { id: 4, title: "ISO Certification Assistance", url: "#" },
          {
            id: 5,
            title: "Intellectual Property Rights Protection",
            url: "#",
            items: [
              { id: 1, title: "Trademark Registration", url: "#" },
              { id: 1, title: "Copyright Registration", url: "#" },
            ],
          },
        ],
      },
      {
        id: 3,
        title: "Insurance Advisory & Coverage",
        links: [
          { id: 1, title: "Business Insurance", url: "#" },
          { id: 2, title: "Health Insurance ", url: "#" },
        ],
      },
      {
        id: 4,
        title: "Legal Services",
        links: [
          { id: 1, title: "Shareholder Agreement Drafting", url: "#" },
          { id: 2, title: "HR Policy Drafting", url: "#" },
          { id: 3, title: "Board Resolution Drafting", url: "#" },
          {
            id: 4,
            title: "Corporate Governance ",
            url: "#",
            items: [
              {
                id: 1,
                title: "Corporate Structuring & Restructuring",
                url: "#",
              },
              {
                id: 1,
                title: "Company Liquidation & Deregistration",
                url: "#",
              },
            ],
          },
        ],
      },
      {
        id: 5,
        title: "Operational Services",
        links: [
          { id: 1, title: "IT Services", url: "#" },
          { id: 2, title: "Mail Management", url: "#" },
          { id: 3, title: "Virtual Receptionist", url: "#" },
          { id: 4, title: "HR & Recruitment Assistance", url: "#" },
          { id: 5, title: "Document Management & Filing Services", url: "#" },
          { id: 6, title: "Logistics & Courier Coordination", url: "#" },
          { id: 7, title: "Procurement Support", url: "#" },
          { id: 8, title: "Supplier & Vendor Registration Support", url: "#" },
          {
            id: 9,
            title: "Government Tender Registration Assistance",
            url: "#",
          },
        ],
      },
      {
        id: 6,
        title: "Business Solutions",
        links: [
          { id: 1, title: "Company Car Registration", url: "#" },
          { id: 2, title: "Business Plan Preparation", url: "#" },
          { id: 3, title: "Meeting Room Booking & Hosting", url: "#" },
          {
            id: 4,
            title: "Customs Registration (Imported/Exporter Code)",
            url: "#",
          },
          { id: 5, title: "Market Research & Feasibility Study", url: "#" },
          { id: 6, title: "Travel & Visa Support for Executives", url: "#" },
          { id: 7, title: "Local Sponsor Arrangement", url: "#" },
          { id: 8, title: "Local Agent/Partner", url: "#" },
          {
            id: 9,
            title: "Nominee Services",
            url: "#",
            items: [
              { id: 1, title: "Nominee Director Services", url: "#" },
              { id: 2, title: "Nominee Shareholder Services", url: "#" },
              {
                id: 3,
                title: "Corporate Bank Account Opening Assistance",
                url: "#",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 3,
    title: "Banking & Wealth",
    url: "/banking-and-wealth-services-in-uae",
    view: "parentChildGridView",
    items: [
      {
        id: 1,
        title: "Wealth Management",
        url: "#",
        links: [],
      },
      {
        id: 2,
        title: "Bank Account Opening in the UAE",
        url: "#",
        links: [
          { id: 1, title: "Off Shore Bank Account", url: "#" },
          { id: 2, title: "Corporate Bank Account", url: "#" },
          { id: 3, title: "UAE Non Resident Bank Account", url: "#" },
          { id: 4, title: "UAE Resident Bank Account", url: "#" },
        ],
      },
      {
        id: 3,
        title: "Treasury Management",
        url: "#",
        links: [],
      },
      {
        id: 4,
        title: "Corporate Bank Account Opening Assistance",
        url: "#",
        links: [],
      },
    ],
  },
  {
    id: 4,
    title: "Digital & Branding Solutions",
    url: "/digital-and-branding-services-in-uae",
    view: "parentChildGridView",
    items: [
      {
        id: 1,
        title: "Digital Solutions ",
        url: "#",
        links: [{ id: 1, title: "Website Development", url: "#" }],
      },
      {
        id: 2,
        title: "IT Services",
        url: "#",
        links: [
          { id: 1, title: "Domain Name & DNS Management", url: "#" },
          { id: 2, title: "Web Hosting Services", url: "#" },
          { id: 3, title: "Office 365 Subscription", url: "#" },
          { id: 4, title: "Hosted Exchange Mailbox", url: "#" },
          { id: 4, title: "24/7 Tech Support", url: "#" },
        ],
      },
      {
        id: 3,
        title: "Event Planning & Management Services",
        url: "#",
        links: [],
      },
      {
        id: 4,
        title: "Marketing & Branding ",
        url: "#",
        links: [],
      },
    ],
  },
  {
    id: 5,
    title: "Millionaire & Billionaire",
    url: "#",
    view: "childView",
    items: [
      {
        id: 1,
        title: "",
        links: [
          { id: 1, title: "Wealth Management Services", url: "#" },
          { id: 2, title: "Financial Partnerships", url: "#" },
          { id: 3, title: "Affiliates & Partners", url: "#" },
          { id: 4, title: "Will & Trust Preparation Services", url: "#" },
          { id: 5, title: "Private Office", url: "#" },
          { id: 6, title: "Second Citizenship Programs", url: "#" },
          { id: 7, title: "Family Foundation & Trust", url: "#" },
          { id: 8, title: "Family Office Setup", url: "#" },
          { id: 9, title: "Golden Visa UAE", url: "#" },
          { id: 10, title: "Asset Protection", url: "#" },
          { id: 11, title: "Escrow Account Assistance", url: "#" },
        ],
      },
    ],
  },
  {
    id: 6,
    title: "Logistics & Relocation",
    url: "#",
    view: "childView",
    items: [
      {
        id: 1,
        title: "",
        links: [
          { id: 1, title: "Tourist Visa", url: "#" },
          { id: 2, title: "Family Relocation Support", url: "#" },
          { id: 3, title: "Green Visa", url: "#" },
          { id: 4, title: "Golden Visa UAE", url: "#" },
          { id: 5, title: "UAE Residence Visa", url: "#" },
          { id: 6, title: "Investor Visa", url: "#" },
          { id: 7, title: "Mainland Visa", url: "#" },
          { id: 8, title: "Visa Cancellation", url: "#" },
          { id: 9, title: "Employment Visa", url: "#" },
          { id: 10, title: "Free Zone Visa", url: "#" },
          { id: 11, title: "Partner Visa", url: "#" },
          { id: 12, title: "Maid Visa", url: "#" },
        ],
      },
    ],
  },
];

export const navDataAr = [
  {
    id: 1,
    title: "إعداد الأعمال",
    url: "/business-setup-services-in-uae",
    view: "tabView",
    tabs: [
      {
        id: 1,
        title: "المنطقة الحرة بالإمارات",
        url: "#",
        items: [
          {
            id: 1,
            title: "منطقة دبي الحرة",
            url: "#",
            links: [
              { id: 1, title: "منطقة المطار الحرة دبي", url: "#" },
              { id: 2, title: "منطقة السيارات دبي", url: "#" },
              { id: 3, title: "مدينة الإنترنت دبي", url: "#" },
              { id: 4, title: "مدينة الإعلام دبي", url: "#" },
              { id: 5, title: "مركز دبي للسلع المتعددة", url: "#" },
              { id: 6, title: "واحة دبي السيليكون", url: "#" },
              {
                id: 7,
                title: "دبي الجنوب - المنطقة الحرة دبي الجنوب",
                url: "#",
              },
              { id: 8, title: "مركز التكنولوجيا الريادي دبي", url: "#" },
              { id: 9, title: "مركز التجارة العالمية دبي", url: "#" },
              { id: 10, title: "منطقة إكسبو سيتي دبي الحرة", url: "#" },
              { id: 11, title: "الهيئة الدولية للمنطقة الحرة", url: "#" },
              { id: 12, title: "منطقة ميدان الحرة", url: "#" },
              {
                id: 13,
                title: "تيكوم - مجموعة التكنولوجيا والإعلام",
                url: "#",
              },
            ],
          },
          {
            id: 2,
            title: "منطقة أبوظبي الحرة",
            url: "#",
            links: [
              { id: 1, title: "سوق أبوظبي العالمي", url: "#" },
              { id: 2, title: "منطقة خليفة الصناعية أبوظبي", url: "#" },
              { id: 3, title: "تو فور 54 (الإعلام والإبداع)", url: "#" },
              { id: 4, title: "مدينة مصدر الحرة", url: "#" },
              { id: 5, title: "منطقة مطار أبوظبي الحرة", url: "#" },
            ],
          },
          {
            id: 3,
            title: "منطقة الشارقة الحرة",
            url: "#",
            links: [
              { id: 1, title: "مدينة النشر الشارقة الحرة", url: "#" },
              { id: 2, title: "منطقة حمرية الحرة", url: "#" },
              { id: 3, title: "المنطقة الدولية مطار الشارقة", url: "#" },
              { id: 4, title: "مدينة الإعلام الشارقة الحرة", url: "#" },
            ],
          },
          {
            id: 4,
            title: "منطقة عجمان الحرة",
            url: "#",
            links: [{ id: 1, title: "عجمان ميديا سيتي الحرة", url: "#" }],
          },
          {
            id: 5,
            title: "منطقة رأس الخيمة الحرة",
            url: "#",
            links: [
              { id: 1, title: "المنطقة الاقتصادية رأس الخيمة", url: "#" },
              { id: 2, title: "مدينة رأس الخيمة البحرية الحرة", url: "#" },
              { id: 3, title: "واحة رأس الخيمة للأصول الرقمية", url: "#" },
            ],
          },
          {
            id: 6,
            title: "منطقة أم القيوين الحرة",
            url: "#",
            links: [{ id: 1, title: "المنطقة الحرة أم القيوين", url: "#" }],
          },
          {
            id: 7,
            title: "منطقة الفجيرة الحرة",
            url: "#",
            links: [
              { id: 1, title: "مدينة الفجيرة الإبداعية الحرة", url: "#" },
            ],
          },
        ],
      },
      {
        id: 2,
        title: "البر الرئيسي الإماراتي",
        url: "#",
        view: "childView",
        items: [
          {
            id: 1,
            title: "",
            url: "#",
            links: [
              { id: 1, title: "البر الرئيسي دبي", url: "#" },
              { id: 2, title: "البر الرئيسي أبوظبي", url: "#" },
              { id: 3, title: "البر الرئيسي عجمان", url: "#" },
              { id: 4, title: "البر الرئيسي الشارقة", url: "#" },
            ],
          },
        ],
      },
      {
        id: 3,
        title: "الأنشطة الخارجية الإماراتية",
        view: "childView",
        url: "#",
        items: [
          {
            id: 1,
            title: "",
            url: "#",
            links: [
              { id: 1, title: "دبي الخارجية", url: "#" },
              { id: 2, title: "جبل علي الخارجية", url: "#" },
              { id: 3, title: "رأس الخيمة الخارجية", url: "#" },
              { id: 4, title: "عجمان الخارجية", url: "#" },
            ],
          },
        ],
      },
      {
        id: 4,
        title: "استشارات أنشطة الشركات",
        url: "#",
        items: [],
      },
      {
        id: 5,
        title: "حلول المكاتب",
        view: "childView",
        items: [
          {
            id: 1,
            title: "",
            url: "#",
            links: [
              { id: 1, title: "تأجير مكتب فعلي", url: "#" },
              { id: 2, title: "مكتب مرن / ذكي", url: "#" },
              { id: 3, title: "خدمات المكتب الافتراضي", url: "#" },
              { id: 4, title: "مساحات العمل المشتركة", url: "#" },
            ],
          },
        ],
      },
      {
        id: 6,
        title: "رخصة الأعمال",
        url: "#",
        items: [
          {
            id: 1,
            title: "رخصة المنطقة الحرة",
            url: "#",
            links: [
              { id: 1, title: "رخصة تجارية", url: "#" },
              { id: 2, title: "رخصة عقارية", url: "#" },
              { id: 3, title: "رخصة صناعية", url: "#" },
              { id: 4, title: "رخصة مهنية", url: "#" },
              { id: 5, title: "رخصة مزدوجة", url: "#" },
              { id: 6, title: "رخصة كريبتو وويب3", url: "#" },
              { id: 7, title: "رخصة الفعاليات", url: "#" },
              { id: 8, title: "رخصة التجارة الإلكترونية", url: "#" },
              { id: 9, title: "تصريح فريلانسر", url: "#" },
            ],
          },
          {
            id: 2,
            title: "الرخصة الرئيسية",
            links: [
              { id: 1, title: "رخصة تجارية", url: "#" },
              { id: 2, title: "رخصة عقارية", url: "#" },
              { id: 3, title: "رخصة فعاليات", url: "#" },
              { id: 4, title: "رخصة إلكترونية", url: "#" },
              { id: 5, title: "رخصة كريبتو وويب3", url: "#" },
              { id: 6, title: "رخصة صناعية", url: "#" },
              { id: 7, title: "رخصة مهنية", url: "#" },
            ],
          },
          {
            id: 3,
            title: "رخص العمل",
            links: [
              { id: 1, title: "رخصة تجارية", url: "#" },
              { id: 2, title: "رخصة عقارية", url: "#" },
              { id: 3, title: "رخصة صناعية", url: "#" },
              { id: 4, title: "رخصة مهنية", url: "#" },
              { id: 5, title: "رخصة كريبتو وويب3", url: "#" },
              { id: 6, title: "رخصة فعاليات", url: "#" },
              { id: 7, title: "رخصة إلكترونية", url: "#" },
            ],
          },
        ],
      },
      {
        id: 7,
        title: "خدمات الـ PRO بالإمارات",
        items: [
          {
            id: 1,
            title: "خدمات PRO دبي",
            links: [
              { id: 1, title: "تسجيل حقوق النشر", url: "#" },
              { id: 2, title: "تسجيل الشركة", url: "#" },
              { id: 3, title: "حجز اسم تجاري", url: "#" },
              { id: 4, title: "تسجيل / تجديد العلامة التجارية", url: "#" },
              { id: 5, title: "تسجيل / تجديد الرخصة", url: "#" },
              { id: 6, title: "تسجيل / تقديم ضريبة القيمة المضافة", url: "#" },
              { id: 7, title: "إجاري (تسجيل عقد الإيجار)", url: "#" },
              { id: 8, title: "تسجيل / تقديم الضريبة الشركات", url: "#" },
              { id: 9, title: "تصديق المستندات", url: "#" },
              { id: 10, title: "الترجمة القانونية", url: "#" },
              { id: 11, title: "صياغة التوكيل", url: "#" },
              { id: 12, title: "خدمات التوثيق", url: "#" },
              { id: 13, title: "تقديم تنظيم الجوهر الاقتصادي (ESR)", url: "#" },
              { id: 14, title: "تقديم المالك الفعلي (UBO)", url: "#" },
            ],
          },
          {
            id: 2,
            title: "خدمات PRO أبوظبي",
            links: [
              { id: 1, title: "تسجيل حقوق النشر", url: "#" },
              { id: 2, title: "تسجيل الشركة", url: "#" },
              { id: 3, title: "حجز اسم تجاري", url: "#" },
              { id: 4, title: "تسجيل / تجديد العلامة التجارية", url: "#" },
              { id: 5, title: "تسجيل / تجديد الرخصة", url: "#" },
              { id: 6, title: "تسجيل / تقديم ضريبة القيمة المضافة", url: "#" },
              { id: 7, title: "إجاري (تسجيل عقد الإيجار)", url: "#" },
              { id: 8, title: "تسجيل / تقديم الضريبة الشركات", url: "#" },
              { id: 9, title: "تصديق المستندات", url: "#" },
              { id: 10, title: "الترجمة القانونية", url: "#" },
              { id: 11, title: "صياغة التوكيل", url: "#" },
              { id: 12, title: "خدمات التوثيق", url: "#" },
              { id: 13, title: "تقديم تنظيم الجوهر الاقتصادي (ESR)", url: "#" },
              { id: 14, title: "تقديم المالك الفعلي (UBO)", url: "#" },
            ],
          },
          {
            id: 3,
            title: "خدمات PRO الشارقة",
            links: [
              { id: 1, title: "تسجيل حقوق النشر", url: "#" },
              { id: 2, title: "تسجيل الشركة", url: "#" },
              { id: 3, title: "حجز اسم تجاري", url: "#" },
              { id: 4, title: "تسجيل / تجديد العلامة التجارية", url: "#" },
              { id: 5, title: "تسجيل / تجديد الرخصة", url: "#" },
              { id: 6, title: "تسجيل / تقديم ضريبة القيمة المضافة", url: "#" },
              { id: 7, title: "إجاري (تسجيل عقد الإيجار)", url: "#" },
              { id: 8, title: "تسجيل / تقديم الضريبة الشركات", url: "#" },
              { id: 9, title: "تصديق المستندات", url: "#" },
              { id: 10, title: "الترجمة القانونية", url: "#" },
              { id: 11, title: "صياغة التوكيل", url: "#" },
              { id: 12, title: "خدمات التوثيق", url: "#" },
              { id: 13, title: "تقديم تنظيم الجوهر الاقتصادي (ESR)", url: "#" },
              { id: 14, title: "تقديم المالك الفعلي (UBO)", url: "#" },
            ],
          },
          {
            id: 4,
            title: "خدمات PRO عجمان",
            links: [
              { id: 1, title: "تسجيل حقوق النشر", url: "#" },
              { id: 2, title: "تسجيل الشركة", url: "#" },
              { id: 3, title: "حجز اسم تجاري", url: "#" },
              { id: 4, title: "تسجيل / تجديد العلامة التجارية", url: "#" },
              { id: 5, title: "تسجيل / تجديد الرخصة", url: "#" },
              { id: 6, title: "تسجيل / تقديم ضريبة القيمة المضافة", url: "#" },
              { id: 7, title: "إجاري (تسجيل عقد الإيجار)", url: "#" },
              { id: 8, title: "تسجيل / تقديم ضريبة الشركات", url: "#" },
              { id: 9, title: "تصديق المستندات", url: "#" },
              { id: 10, title: "الترجمة القانونية", url: "#" },
              { id: 11, title: "صياغة التوكيل", url: "#" },
              { id: 12, title: "خدمات التوثيق", url: "#" },
              { id: 13, title: "تقديم تنظيم الجوهر الاقتصادي (ESR)", url: "#" },
              { id: 14, title: "تقديم المالك الفعلي (UBO)", url: "#" },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "الخدمات المؤسسية",
    url: "/corporate-services-in-uae",
    view: "parentChildView",
    items: [
      {
        id: 1,
        title: "خدمات المحاسبة",
        links: [
          { id: 1, title: "إدارة الرواتب", url: "#" },
          { id: 2, title: "استشارات ضريبة القيمة المضافة والضرائب", url: "#" },
          { id: 3, title: "ضريبة الشركات", url: "#" },
        ],
      },
      {
        id: 2,
        title: "خدمات الالتزام القانوني",
        links: [
          { id: 1, title: "شهادة مكافحة غسل الأموال", url: "#" },
          { id: 2, title: "خدمات التدقيق", url: "#" },
          { id: 3, title: "شهادة الإقامة الضريبية", url: "#" },
          { id: 4, title: "مساعدة شهادة ISO", url: "#" },
          {
            id: 5,
            title: "حماية الحقوق الفكرية",
            url: "#",
            items: [
              { id: 1, title: "تسجيل العلامة التجارية", url: "#" },
              { id: 1, title: "تسجيل حقوق النشر", url: "#" },
            ],
          },
        ],
      },
      {
        id: 3,
        title: "استشارات التأمين والتغطية",
        links: [
          { id: 1, title: "تأمين الأعمال", url: "#" },
          { id: 2, title: "تأمين صحي", url: "#" },
        ],
      },
      {
        id: 4,
        title: "الخدمات القانونية",
        links: [
          { id: 1, title: "صياغة اتفاقية المساهمين", url: "#" },
          { id: 2, title: "صياغة سياسات الموارد البشرية", url: "#" },
          { id: 3, title: "صياغة قرارات المجلس", url: "#" },
          {
            id: 4,
            title: "الحوكمة المؤسسية",
            url: "#",
            items: [
              { id: 1, title: "هيكلة وإعادة هيكلة الشركات", url: "#" },
              { id: 1, title: "تصفيّة الشركة وإلغاء التسجيل", url: "#" },
            ],
          },
        ],
      },
      {
        id: 5,
        title: "الخدمات التشغيلية",
        links: [
          { id: 1, title: "خدمات تقنية المعلومات", url: "#" },
          { id: 2, title: "إدارة البريد", url: "#" },
          { id: 3, title: "مكتب استقبال افتراضي", url: "#" },
          { id: 4, title: "مساعدة التوظيف والموارد البشرية", url: "#" },
          { id: 5, title: "إدارة الوثائق والأرشفة", url: "#" },
          { id: 6, title: "تنسيق اللوجستيات والبريد السريع", url: "#" },
          { id: 7, title: "دعم المشتريات", url: "#" },
          { id: 8, title: "دعم تسجيل الموردين والبائعين", url: "#" },
          {
            id: 9,
            title: "مساعدة التسجيل في المناقصات الحكومية",
            url: "#",
          },
        ],
      },
      {
        id: 6,
        title: "حلول الأعمال",
        links: [
          { id: 1, title: "تسجيل سيارة الشركة", url: "#" },
          { id: 2, title: "إعداد خطة عمل", url: "#" },
          { id: 3, title: "حجز غرفة الاجتماعات واستضافتها", url: "#" },
          {
            id: 4,
            title: "التسجيل الجمركي (استيراد / تصدير)",
            url: "#",
          },
          { id: 5, title: "أبحاث السوق ودراسة الجدوى", url: "#" },
          { id: 6, title: "دعم السفر والتأشيرات للإداريين", url: "#" },
          { id: 7, title: "ترتيب الكفيل المحلي", url: "#" },
          { id: 8, title: "شريك / وكيل محلي", url: "#" },
          {
            id: 9,
            title: "خدمات الوكيل الاسمي",
            url: "#",
            items: [
              { id: 1, title: "خدمات مدير اسمي", url: "#" },
              { id: 2, title: "خدمات مساهم اسمي", url: "#" },
              {
                id: 3,
                title: "مساعدة فتح حساب مصرفي للشركة",
                url: "#",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 3,
    title: "الخدمات المصرفية والثروات",
    url: "/banking-and-wealth-services-in-uae",
    view: "parentChildGridView",
    items: [
      {
        id: 1,
        title: "إدارة الثروات",
        url: "#",
        links: [],
      },
      {
        id: 2,
        title: "فتح حساب مصرفي بالإمارات",
        url: "#",
        links: [
          { id: 1, title: "حساب مصرفي خارجي", url: "#" },
          { id: 2, title: "حساب مصرفي للشركات", url: "#" },
          { id: 3, title: "حساب مقيم غير مقيم الإمارات", url: "#" },
          { id: 4, title: "حساب مقيم الإمارات", url: "#" },
        ],
      },
      {
        id: 3,
        title: "إدارة الخزينة",
        url: "#",
        links: [],
      },
      {
        id: 4,
        title: "مساعدة فتح حساب مؤسسي مصرفي",
        url: "#",
        links: [],
      },
    ],
  },
  {
    id: 4,
    title: "الحلول الرقمية والعلامة التجارية",
    url: "/digital-and-branding-services-in-uae",
    view: "parentChildGridView",
    items: [
      {
        id: 1,
        title: "الحلول الرقمية",
        url: "#",
        links: [{ id: 1, title: "تطوير مواقع", url: "#" }],
      },
      {
        id: 2,
        title: "خدمات تكنولوجيا المعلومات",
        url: "#",
        links: [
          { id: 1, title: "إدارة النطاق و DNS", url: "#" },
          { id: 2, title: "استضافة المواقع", url: "#" },
          { id: 3, title: "اشتراك Office 365", url: "#" },
          { id: 4, title: "صندوق بريد Hosted Exchange", url: "#" },
          { id: 5, title: "دعم تقني 24/7", url: "#" },
        ],
      },
      {
        id: 3,
        title: "تنظيم وإدارة الفعاليات",
        url: "#",
        links: [],
      },
      {
        id: 4,
        title: "التسويق والعلامة التجارية",
        url: "#",
        links: [],
      },
    ],
  },
  {
    id: 5,
    title: "المليونيرات والمليارات",
    url: "#",
    view: "childView",
    items: [
      {
        id: 1,
        title: "",
        links: [
          { id: 1, title: "خدمات إدارة الثروات", url: "#" },
          { id: 2, title: "الشراكات المالية", url: "#" },
          { id: 3, title: "شركاء و Affiliates", url: "#" },
          { id: 4, title: "إعداد الوصية والثقة", url: "#" },
          { id: 5, title: "المكتب الخاص", url: "#" },
          { id: 6, title: "برامج المواطنة الثانية", url: "#" },
          { id: 7, title: "مؤسسة العائلة والثقة", url: "#" },
          { id: 8, title: "إنشاء مكتب عائلي", url: "#" },
          { id: 9, title: "الفيزا الذهبية الإماراتية", url: "#" },
          { id: 10, title: "حماية الأصول", url: "#" },
          { id: 11, title: "مساعدة الحساب الضمان", url: "#" },
        ],
      },
    ],
  },
  {
    id: 6,
    title: "اللوجستيات والنقل",
    url: "#",
    view: "childView",
    items: [
      {
        id: 1,
        title: "",
        links: [
          { id: 1, title: "تأشيرة سياحية", url: "#" },
          { id: 2, title: "دعم انتقال العائلة", url: "#" },
          { id: 3, title: "الفيزا الخضراء", url: "#" },
          { id: 4, title: "الفيزا الذهبية الإماراتية", url: "#" },
          { id: 5, title: "فيزا الإقامة الإماراتية", url: "#" },
          { id: 6, title: "فيزا المستثمر", url: "#" },
          { id: 7, title: "فيزا البر الرئيسي", url: "#" },
          { id: 8, title: "إلغاء التأشيرة", url: "#" },
          { id: 9, title: "فيزا العمل", url: "#" },
          { id: 10, title: "فيزا المنطقة الحرة", url: "#" },
          { id: 11, title: "فيزا الشريك", url: "#" },
          { id: 12, title: "فيزا الخادمة", url: "#" },
        ],
      },
    ],
  },
];
