export const icons = {
    threeDots: "mdi:dots-vertical",
    search: "iconamoon:search",
    notification: "ion:notifications-outline",
    navMenu: "ic:round-menu",
    loading: "eos-icons:bubble-loading",
    calendar: "solar:calendar-bold",
    share: "fa-solid:share",
    print: "fa6-solid:print",
    upArrow: "ep:top",
    'upArrowv2': "material-symbols:arrow-drop-up",
    downArrow: "ep:bottom",
    'downArrowv2': "material-symbols:arrow-drop-down",
    logout: "line-md:log-out",
    star: "mdi:star-outline",
    'starV2': "iconoir:star-solid",
    edit: "akar-icons:edit",
    plus: "icons8:plus",
    refresh: "tdesign:refresh",
    checkBox: "octicon:check-16",
    mobile: "uiw:mobile",
    laptop: "ant-design:laptop-outlined",
    accessories: "bx:headphone",
    upload: "solar:gallery-broken",
    remove: "line-md:remove",
    delete: "material-symbols-light:delete",
    restore: "fluent-mdl2:update-restore",
    add: "ri:add-box-fill",
    percent: "iconamoon:sign-percent-bold",
    cancel: "proicons:cancel",
    view: "hugeicons:view",

    ship: "hugeicons:shipping-truck-01",
    shipmentLabel: "hugeicons:label",
    shipmentTrack: "hugeicons:van",
}